[package]
name = "overflower_support"
version = "0.1.0"
authors = ["Andre Bogus <bogusandre@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/llogiq/overflower"
keywords = ["arithmetic", "overflow"]
