[package]
name = "overflower"
version = "0.1.0"
authors = ["Andre Bogus <bogusandre@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/llogiq/overflower"
readme = "README.md"
keywords = ["arithmetic", "overflow", "plugin"]

[dependencies]
overflower-support = { version = "*", path = "support" }
